### ISSUE TITLE
create docset for RFC

### ISSUE THREAD

**Issue by stardiviner** [areina/helm-dash#100]
Is there an docset for RFC? if not how to create?

**Comment by kidd** [comment]
oh, nice idea.
I see https://github.com/willnorris/rfcdash that should work.  I haven't tried it though

**Comment by areina** [comment]
Hey @stardiviner, did you already try that docset ?  I think you can install it with `helm-dash-install-user-docset`, it is there as `RFCs`. 

I'm going to close the issue, but feel free to reopen it if something doesn't work well.
