### ISSUE TITLE
helm-dash should list google engine when pattern not found

### ISSUE THREAD

**Issue by gfZeng** [areina/helm-dash#101]
I want to search a pattern from docset, but not found. In this case, I want search it via google.

**Comment by areina** [comment]
Hey, thanks but that isn't the purpose of helm-dash. Take a look at https://github.com/steckerhalter/helm-google . Maybe you can hack something to combine both.

**Comment by kidd** [comment]
maybe hacking something around helm-dash-actions .... but no idea, and as @areina says, it's not the main purpose of helm-dash ...
