### ISSUE TITLE
autoload 'helm-dash-activate-docset

### ISSUE THREAD

**Issue by jwintz** [areina/helm-dash#109]
Hello,

In my config, I do not set `helm-dash-common-docsets` as it forces my to download all of them whenever I clone my emacs configuration from a machine to another.

So I like to use `helm-dash-install-docset` interactively, but subsequently, `helm-dash` does not provide any candidate unless If i activate it via `helm-dash-activate-docset`. Unfortunately this function is only invokable once `helm-dash` has been called once. So the workflow is broken. It would be very nice to autoload `helm-dash-activate-docset` so that the workflow could be:

1. `helm-dash-install-docset`
2. `helm-dash-activate-docset`
3. `helm-dash`

Thanks !

**Comment by jwintz** [comment]
Great ! Thanks @kidd and @areina ! How long before it ends on Melpa ?

**Comment by kidd** [comment]
it should be there automatically after it's merged. maybe they build it themselves, but it shouldn't take long anyway

**Comment by areina** [comment]
It isn't available immediately. They execute a build periodically, but I don't know the interval.
Currently melpa.org shows this message: 
> Current build started: 4 hours ago, last took 4 hours
