### ISSUE TITLE
give user a hint when helm-dash ins quering or when no result

### ISSUE THREAD

**Issue by stardiviner** [areina/helm-dash#112]
I don't know what helm-dash is doing, when just blank result. still quering, or just no result.
I mean I want to know helm-dash's status.
helm-dash can show status info in mode-line, or somewhere else. (minibuffer (echo-area) is already been used by input).

**Comment by kidd** [comment]
from my experience, results show nearly instantaneously. if you have enough time to look at the mode line, probably it's a "no results".  Still, if you provide a PR, it can easily be merged :)

**Comment by stardiviner** [comment]
I use custom mode-line. I will add helm-dash mode-line update code by myself.
Sometimes is is fast, sometimes it is slow. For example, I delete word, and input a new word, helm-dash start query again.

**Comment by stardiviner** [comment]
And when I don't specify docset name, the query will be slow. Helm-dash will query all docsets.

**Comment by kidd** [comment]
Slow as in what? I have 5 to 10 docsets, and it's not that slow on my machine. liks, sub-second slow.
