### ISSUE TITLE
New release for melpa-stable

### ISSUE THREAD

**Issue by sometimesfood** [areina/helm-dash#114]
The last release of helm-dash on melpa-stable (1.1.0) does not work with current helm versions:

    helm-dash.el:41:1:Error: Cannot open load file: no such file or directory, helm-match-plugin

This error seems to have been fixed in 4e1046f72e116b56bb23fed0e22f9a2907f5485e.

Could you please release a new version of helm-dash for the melpa-stable users out there? Thanks!

**Comment by kidd** [comment]
Done!. 

Thanks for noticing!

**Comment by sometimesfood** [comment]
Great, works like a charm. Thanks for the fast response!
