### ISSUE TITLE
Issue when using `helm-dash-install-docset-from-file`

### ISSUE THREAD

**Issue by meditans** [areina/helm-dash#117]
Hi, I created a custom docset named `target.docset` (which is a folder) in the folder of one of my projects. When I'm into that project, I want to use that docset.

However, when I try the function `helm-dash-install-docset-from-file`, I get in the minibuffer the string `Docset installed. Add "tar: Error is not recoverable: exiting now" to helm-dash-common-docsets or helm-dash-docsets.` and I get no results in the `helm-dash` search.

What am I missing here? What is the recommended workflow to have a custom docset per project?

**Comment by meditans** [comment]
The missing link might be the instruction:

    tar --exclude='.DS_Store' -cvzf <docset name>.tgz <docset name>.docset

to generate a `tgz` file for the docset.

**Comment by kidd** [comment]
Right, the docs were not explicit about this. Thank  you for the PR. It's merged
