### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by quimmeetpays** [areina/helm-dash#120]
Is there a way to choose the docset language? I'm using PHP, and documentation is available in multiple languages, but installing the PHP docset only gives access to the english language documentation.

**Comment by kidd** [comment]
mmm.... afaik docsets are not aware of languages. Could you try to inspect the sqlite db that gets downloaded a bit?

If not, you can always create your own docset and install it manually.

**Comment by quimmeetpays** [comment]
That's right. I'll try to create my own docset. The sqlite db contains only the english version.

Thank you.
