### ISSUE TITLE
Narrowing is only happening within the initial 1000 index values

### ISSUE THREAD

**Issue by jonesej** [areina/helm-dash#124]
(disclaimer - I'm very new to helm-dash, so it's definitely within the realm of possibility that I'm just using it wrong).

I've installed helm-dash through melpa (version 20160220.435) and the Java_SE8 docset using helm-dash-install-docset.

To try it out I executed helm-dash and at the "Doc for:" prompt, I tried to type "FileNotFoundException". As I typed "Fil", the choice of "File" came up, but once I got to typing "FileN", all choices were gone.
Further testing showed that no docs are reachable beyond the initial 1000 that comes up when I type "Java" in the 'Doc for:' prompt.

emacs version 24.4.1
helm version 20160126.1110

**Comment by kidd** [comment]
Thanks for the report, I found out that it's  regression that appeared on the last release.
I'm working on a fix, so in a couple of days it should be solved.

**Comment by jonesej** [comment]
I finally got around to trying it again. It works good. Thanks!
