### ISSUE TITLE
helm-dash-build-source: Invalid function: (docset docset)

### ISSUE THREAD

**Issue by marcinant** [areina/helm-dash#127]
Hi!

I followed manual. Installed and activated PHP docset and when I try 'helm-dash' I get message as in topic.

**Comment by kidd** [comment]
Can you check that you have 'lexical-let' macro available? If not, try (require 'cl), eval helm-dash, and try m-x helm-dash again.

Thanks

**Comment by marcinant** [comment]
No, I don't have 'lexical-let'. However I solved this problem adding 
```
;;; -*- lexical-binding: t -*-
```
to helm-dash.el as described in [Emacs Wiki](https://www.emacswiki.org/emacs/DynamicBindingVsLexicalBinding)

**Comment by kidd** [comment]
We should probably add this to the file.  
If you feel like issuing a PullRequest, we'll merge it instantly, if not, I'll do it later today (I hope)
