### ISSUE TITLE
helm-plugin not found

### ISSUE THREAD

**Issue by jvillasante** [areina/helm-dash#135]
When using either `helm-dash` or `helm-dash-at-point` I get the following error:

> Cannot open load file: No such file or directory, helm-plugin

I'm using spacemacs and helm is installed
Anyone?

**Comment by jwintz** [comment]
Fixed in #134.

**Comment by kidd** [comment]
yup, fixed there. :)

**Comment by jvillasante** [comment]
yes, it is fixed. But package not on melpa yet!

**Comment by jwintz** [comment]
> Current build started: 2 hours ago, last took 3 hours

Just wait a little bit ;-)
