### ISSUE TITLE
Use docsets from Zeal

### ISSUE THREAD

**Issue by sanklamm** [areina/helm-dash#140]
Since I am on Windows, I have to use Zeal as my document browser. Zeal creates a subfolder /Doc where all docsets live in. Like so:
"../Zeal/Doc/Python_3.docset"
I understand that these are the same as in dash?
Is there a way to use these docsets with helm-dash? I already tried:
(setq helm-dash-docsets-path "C:/Users/my.name/Apps/ZealPortable/Doc/")

**Comment by kidd** [comment]
Changing helm-dash-docsets-path should work. not sure what is the correct path, but it should be definately possible. 

Btw, you don't need zeal. helm-dash uses sqlite3 (that one you do need) to directly search in the docsets.

**Comment by sanklamm** [comment]
I will try again tomorrow.
Is it true that if the helm-dash-docset-path is correctly set that I would see a list of all docsets when I call helm-dash-docset-activate (I don't have the correct function in front of me)?

Is it enough to set the PATH of sqlite in my emacs config or does it need to be set in Windows?

**Comment by sanklamm** [comment]
I changed helm-dash-docsets-path with  
`(setq helm-dash-docsets-path "C:/Users/my.name/AppData/Roaming/.emacs.d/docsets")`  
I checked if the path was right with  
`(directory-files "C:/Users/my.name/AppData/Roaming/.emacs.d/docsets")`  
which listed the `*.docset` files. But when I used   
`helm-dash-activate-docset`  
the list was empty. What am I doing wrong? I also have sqlite3 in my PATH.

**Comment by kidd** [comment]
Hi,
you should (helm-dash-activate-docset "Python_3")  or "Python 3", depends on the name of the directory.

then, (helm-dash) should open helm-dash with the python docset.

some errors write info in some *helm-dash-errors* buffer.  maybe it has useful info.

**Comment by sanklamm** [comment]
That just returns nil.

**Comment by kidd** [comment]
just returns nil? It should at least open the dash interface.

if you have some elisp-fu, try toggle-debug-on-errors, or tracing some functions (I have no windows to try)

**Comment by sanklamm** [comment]
you mean the app Dash? I don't have that since I am on Windows. That's why I used Zeal, which fetches the same docsets. I am trying to access those.

**Comment by kidd** [comment]
sorry, I ment the helm interface

**Comment by sanklamm** [comment]
yes. it opens the empty helm interface. I guess this would list all docsets in the specified folder. A search for an existing docset ("Python_3" or "Bash") returns "no match".

**Comment by kidd** [comment]
it doesn't list all docsets in the folder. you have to 'activate' them, putting them in helm-dash-active-docsets list.

Then they should be searched when searching for a term. I don't know what should be the output of looking for 'bash'. try looking for 'print' or 'echo'.    also, trace-functions.

**Comment by sanklamm** [comment]
ok. At least I got helm-dash to find the docsets now. But it isn't able to load the docs. I think either the docsets generated by Dash on the Mac are different than the ones on Windows or the way you deep-link to a specific section in a html file is different on both systems. I hereby declare this experiment as failed.

**Comment by sanklamm** [comment]
Tomorrow I'll transfer a few docsets from my Mac to the Windows machine and check again.

**Comment by sanklamm** [comment]
Right. I got it (partly) to work. If helm-dash uses an external browser, it can open the docs. But I want to use eww (thats why I picked helm-dash over zeal-at-point in the first place).
Sadly eww is not able to resolve local file URLs. It opens a ftp connection and thinks "c:" in the path c:/User/... is a host.
Don't know, is that your business how you pipe URLs to eww or is that eww's fault?

Thanks for your time.

**Comment by kidd** [comment]
the docsets are exactly the same. they are tgz files (which helm-dash can also download without zeal/dash).

Good luck with your next experiments. keep us informed

**Comment by kidd** [comment]
eww has some issues (in mac at least, see helm-dash readme).  

so, it's either windows' , or your config (maybe you have to escape c:\ somehow), or eww's . 

zeal-at-point and helm-dash approaches are quite different. Use what works best for you.

**Comment by sanklamm** [comment]
Yes, I know. Do you - by any chance - know of someone who got helm-dash to work on windows? With opening the docs inside emacs that is?

**Comment by sanklamm** [comment]
It seems w3n is the way to go instead of eww. w3n is able to resolve the URLs properly. But getting w3n to work on Windows involves a couple of extra steps. Especially with spacemacs as there is no w3n layer available.  
But it works now and I'm happy with it. Thanks again for your time.
