### ISSUE TITLE
 zeal-at-point doesn't work with Emacs Lisp docset

### ISSUE THREAD

**Issue by JAremko** [areina/helm-dash#142]
With Emacs lisp  `zeal-at-point` shows nothing and the search string is `emacs lisp:let` - *if (let... is at point*. It's probably because  Emacs Lisp docset(http://sanfrancisco.kapeli.com/feeds/Emacs_Lisp.tgz ) has white space in the docset folder name.

**Comment by JAremko** [comment]
Whoops. I realised that it's probably different package :smile:

**Comment by kidd** [comment]
Heh,

Maybe helm-emacs is the solution :)
