### ISSUE TITLE
Android docset is broken

### ISSUE THREAD

**Issue by rlazo** [areina/helm-dash#145]
I just updated the Android docset and the URL it tries to navigate to is

`file:///home/me/.docsets/Android.docset/Contents/Resources/Documents/developer.android.com/reference/java/util/concurrent/atomic/AtomicReference.html%3Cdash_entry_menuDescription=java.util.concurrent.atomic.AtomicReference%3E`

For some reason the 

`%3Cdash_entry_menuDescription=java.util.concurrent.atomic.AtomicReference%3E`

gets appended to the URL. Removing it fixes the issue

**Comment by areina** [comment]
Hi @rlazo , I reproduced the issue, I'm going to prepare a fix. Thanks for report it!
