### ISSUE TITLE
New release of helm-stable

### ISSUE THREAD

**Issue by sometimesfood** [areina/helm-dash#151]
The last released version of helm-dash (1.2.0) does not work with current versions of helm (2.7.0) since it requires `'helm-plugin`.

Could you please release a new version of helm-dash in order to fix this?

As far as I can tell it should be sufficient to remove the offending line from `helm-dash.el`. At least I haven't encountered any problems with that small modification yet.

**Comment by wmealing** [comment]
I also commented this out with no adverse affect that i was able to notice.

**Comment by kidd** [comment]
ooops. It seems we forgot this one.... :(

yes, I'll try to fix it asap.

**Comment by kidd** [comment]
finally did it. :sweat_smile: . pushed tag 1.3.0 . melpa stable should do its magic shortly

**Comment by sometimesfood** [comment]
Thanks! Seems to be working great for me. 👍
