### ISSUE TITLE
New function to install docsets if they are not yet installed

### ISSUE THREAD

**Issue by sometimesfood** [areina/helm-dash#152]
I like to add my list of docsets to be installed to my Emacs config in order to share them between multiple systems.

In order to do that, I wrote a simple function named `helm-dash-ensure-docset-installed` which is used like this:

```elisp
(helm-dash-ensure-docset-installed "Ansible")
```

Would you be interested in including something similar in `helm-dash`? I could add some documentation and submit a pull request if you are interested.

```elisp
(defun helm-dash-docset-installed-p (docset)
  (member docset (helm-dash-installed-docsets)))

(defun helm-dash-ensure-docset-installed (docset)
  (unless (helm-dash-docset-installed-p docset)
    (helm-dash-install-docset docset)))
```

**Comment by kidd** [comment]
I think it's a nice helper function and I'd be happy to have it inside helm-dash.

**Comment by sometimesfood** [comment]
Great, happy to hear that!

I'll add some documentation and submit a pull request, then.

**Comment by sometimesfood** [comment]
Sorry for the long delay.

Just submitted a pull request (#153). Closing this issue.
