### ISSUE TITLE
auto filter docs with current major mode

### ISSUE THREAD

**Issue by amosbird** [areina/helm-dash#154]
When in rust mode, I'd like to only search for rust docs, however I get this ![](https://la.wentropy.com/KJEE.png)

**Comment by amosbird** [comment]
Ok, the prefix doc source filter works, but it cannot contain a space. `Emacs Lisp` doesn't work.

**Comment by kidd** [comment]
Hi,
you can use this to add docsets depending on the modes (while having some common ones). https://github.com/areina/helm-dash#buffer-local-docsets . 

you can set-local the helm-dash-common-docsets variable and have complete control over what is available in  each buffer.

**Comment by amosbird** [comment]
@kidd Thanks!
