### ISSUE TITLE
Feature request: additional helm-dash-candidate-format

### ISSUE THREAD

**Issue by jesuspc** [areina/helm-dash#160]
Currently there are three format tokens available: 

%d - docset name
%n - name of the token
%t - type of the token

Even when using all of those there are still circumstances in which a search pattern outputs multiple results that can not be distinguished. For instance:

<img width="1280" alt="screen shot 2017-09-04 at 20 52 52" src="https://user-images.githubusercontent.com/2353002/30037655-f5e9641e-91b4-11e7-80ee-5143a5e34066.png">

That's the same search pattern result in the Dash UI:

<img width="935" alt="screen shot 2017-09-04 at 20 53 13" src="https://user-images.githubusercontent.com/2353002/30037657-f79dc5fc-91b4-11e7-82f2-843c1b747295.png">

Note that in the second case there is additional information available (the module where the function is defined).

Would it be possible to provide additional candidate-format tokens so the additional information that is shown in the Dash.app also appears in the helm buffer?

**Comment by kidd** [comment]
Yes, it probably can be added. 

We should take a look at the table structure of those docsets and see where to fetch that data.

**Comment by kidd** [comment]
I have a working solution that solves this, but I'm afraid there can be a performance degradation. I'll push it in a branch and we should try it for some time.  

I'm probably hairsplitting, but want to be sure that for normal cases there is no noticeable delay (ill-formed strings would probably show the delay, but f*ckit)

**Comment by kidd** [comment]
there you go. test it in that branch for now. https://github.com/areina/helm-dash/pull/161

**Comment by jesuspc** [comment]
That's great! Thanks!

<img width="1280" alt="screen shot 2017-09-06 at 19 32 37" src="https://user-images.githubusercontent.com/2353002/30128340-35802c30-933a-11e7-97f4-eb8d611d895e.png">

**Comment by kidd** [comment]
I'm merging it for now. If it becomes a performance issue, we can optimize it by evaluating %f lazily.
