### ISSUE TITLE
Never finishes installing docset

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [areina/helm-dash#167]
I am on Debian 9. I installd sqlite3 and helm dash. Installing some docsets (`html` `emacs lisp`) takes a while but is O.K. However when I try to install the `C` docset for example, emacs uses 97% of my cpu and has taken so long that I've had to kill it. Is there some alternative thing I can do to install such docsets?

**Comment by kidd** [comment]
Hi Luis,
I just tried it and it's working fine here. Is it consistently failing in your box? it might have been some hiccup in the connection. elisp http client is not very reliable in that aspect.

If you get the docset gzip you can use (helm-dash-install-docset-from-file "/path/to/file.gz")

**Comment by Luis-Henriquez-Perez** [comment]
Hi @kidd,
It is consistently failing. I've tried it 4 separate times (one of those just now again). Other packages that connect to the internet (w3m eww) seem to connect fine. The last message displayed is `Contacting host: sanfrancisco.kapeli.com:80` and then CPU usage flies to 99%. I don't to get the gzip so I'm looking up online how to do it but once I get it I'll let you know how `helm-dash-install-docset-from-file` goes.

**Comment by Luis-Henriquez-Perez** [comment]
Ok. I just downloaded `Zeal` and used it to get the `C.docset` file and moved it to the `.docset` folder. I know, kind of defeats the purpose but works for now. Also let me know what I can do to show you a reproduction of the issue I'm having. Would dropping a `gif` with the steps I take work so you can see what's happening for yourself? Or would you prefer more system specs?

**Comment by Luis-Henriquez-Perez** [comment]
After leaving this issue for a while and returning to it, my hypothesis is that helm-dash is actually installing the docset, but that just takes a really long time and a many resources on my machine. 
When I installed the `Emacs-Lisp` and 'Clojure' docsets, it did so very quickly (perhaps because it's smaller). When I installing `Haskell` and `C` docsets it took much longer but eventually worked.

I will note that I have a pretty outdated computer in terms of specifications. My cpu is an `Intel 2 P8600` which according to cpu benchmark 1538 which is pretty low.

**Comment by kidd** [comment]
Oh... yes, from what I see, the decompressed haskell docset is 1/2 Gb, and C is 300Mb, so yes, this might be it.

Thanks for passing by and writing your findings.

Cheers
