### ISSUE TITLE
How to narrow down to one specific docset?

### ISSUE THREAD

**Issue by balalaXD** [areina/helm-dash#180]
According to document:

    To narrow the search to just one docset, type its name in the beginning of the search followed by a space.
    If the docset contains spaces, no problemo, we handle it :D.

Edebug with:
https://github.com/areina/helm-dash/blob/0ac2db529577fa63f2ed32310062873c585b91de/helm-dash.el#L428-L439

After run `M-x helm-dash`, stop at `(defun helm-dash-maybe-narrow-docsets (pattern)`, then prompt `Doc for: `

Questions:
1. Why `helm-dash-maybe-narrow-docsets` run before prompt `Doc for:`, i have not type anything yet...
2. Where `helm-pattern` come from? How to change the value?
https://github.com/areina/helm-dash/blob/0ac2db529577fa63f2ed32310062873c585b91de/helm-dash.el#L556-L563
3. How to narrow down to one specific docset?
![2019-02-19-125507_1920x1080_scrot](https://user-images.githubusercontent.com/16096559/52991717-d063c580-3448-11e9-804a-14cd5794e152.png)

i am not familiar with `helm` :smile: thanks

**Comment by kidd** [comment]
`helm-pattern` is the 'global' variable that contains the text the user wrote as input to helm.

Not sure, but maybe the search for the docset is case sensitive. Try with exact matching case, and if it works, we can work on making it case insensitive if it makes sense (I think it does)
