### ISSUE TITLE
Mac gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by ksjogo** [areina/helm-dash#24]
I tried to install the Common Lisp and the CoffeeScript docs on Mac OS X 10.8. Both failed with this error message 

```
gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.
```

Afterwards calling helm-dash will result in

```
esqlite--error: esqlite: "unable to open database \"~/.docsets/Common_Lisp.docset/Contents/Resources/docSet.dsidx\": unable to open database file
"

```

**Comment by gavenkoa** [comment]
Have same error on Debian Sid. After some time Emacs crashed.

Updating **libgnutls** packages fix error:

    $ tail /var/log/apt/history.log
    Start-Date: 2015-02-19  19:00:54
    Upgrade: libgnutls-deb0-28:i386 (3.3.8-3, 3.3.8-5), libgnutls26:i386 (2.12.20-1, 2.12.23-18), libgnutls-openssl27:i386 (2.12.20-1, 3.3.8-5)
    End-Date: 2015-02-19  19:01:00

**Comment by E3D3** [comment]
Same issue on Manjaro Linux:
gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.
The files are not downloaded.
