### ISSUE TITLE
Finding a way to support Windows

### ISSUE THREAD

**Issue by MatthewDarling** [areina/helm-dash#35]
I know, I know, boo Windows, but let's see if we can't figure this out.
## tar and weird paths

Emacs seems to do a good job of handling weird paths: for instance, `directory-files` correctly lists the files for the string `"C:\\Users\\Matt\\/.docsets"`. So that's great, but external programs will have trouble with that.

Sadly, there may need to be two special cases for Windows users here: one for people who use Cygwin, and one for more Windows-like versions of Unix programs (GnuWin32, UnixUtils, MsysGit, etc). I use Cygwin, so what follows works for me, but it should probably be the backup case if the default fails.

The first hangup is when using `helm-dash-install-docset`. Under Cygwin, the only way I could get tar to work was to use the `cygpath` program to convert the target file to an absolute path. `helm-dash-docsets-path` seems to work as-is though, strangely. Working example, with a pre-downloaded archive:

```
(let ((testing "C:\\Users\\Matt\\.docsets\\LaTeX.tar.bz2"))
    (shell-command-to-string (format "tar xvf %s -C %s"
        (s-trim (shell-command-to-string 
            (format "cygpath -a %s" testing))) helm-dash-docsets-path)))
```

With cygpath, -a generates absolute paths, and it looks like `shell-command-to-string` keeps the trailing newline, so I'm trimming that with s.el.

If I add a call to cygpath in `helm-dash-install-docset`, I can in fact get docsets installed. Yay! But I don't know the best way to conditionally activate the cygpath conversion. Maybe try tar without, then it if fails, check for a cygpath executable on $PATH, and use it if one is found?

That is, assuming other distributions of Unix utilities opt for a more Windows-like approach, and should handle normal Windows paths. That being said, I've tested a bit with the MsysGit version of `tar`, and it seems to suck just as much as the Cygwin version - I couldn't get it to work at all with any absolute path, only relative ones. Sigh.
## Beyond tar

With the Emacs Lisp docset installed, and this line executed:

`(setq helm-dash-common-docsets '("Emacs Lisp"))`

I don't get any results from running `helm-dash`, no matter what I type. I've installed esqlite, and pcsv, and they seem to at least load correctly. I'm not getting any error messages or warnings. At this stage, I don't have an easy guess for what the error might be. I'd be happy to test any likely sources of errors, though :)

**Comment by jeeger** [comment]
Thanks to the other people in this thread, I have gotten helm-dash to work on Windows.

The key requirement was having a new enough version of tar (1.23 works, 1.13 was too old), and adding the `--force-local` argument to `tar` (this should be added on all platforms, as it won't make a difference on Linux and Mac OS). I've installed all dependencies via scoop.

I've also replaced the `url-` functions used in helm-dash with calls to `curl`, as I am behind a forced proxy, and Emac's proxy handling leaves some things to be desired. My fork with very smal fixes is available at https://github.com/jeeger/helm-dash/tree/windows-fixes.

**Comment by jeeger** [comment]
And an additional wrinkle of docsets containing files with invalid file name characters on NTFS (`<>:"/\\|?*`). I've tried fixing this with the GNU tar `--transform` option only on windows systems. To see an example for invalid characters, look inside the C docset, where there are several files that have a colon in their name. I've implemented this in jeeger/helm-dash@279fa5c76be9512f10c167b7fe7b4996f9453736.

**Comment by fleimgruber** [comment]
Good job @jeeger! do you plan to make a PR?

**Comment by jeeger** [comment]
It's available in PR #181.

**Comment by kidd** [comment]
That's awesome! thanks!

**Comment by kidd** [comment]
#181 has been merged! :tada:

**Comment by kidd** [comment]
@fleimgruber, could you try the latest version and tell us how it worked for you?

**Comment by fleimgruber** [comment]
Using `helm-dash-20190316.2009` from MELPA works for me with docsets downloaded using Zeal.

**Comment by jeeger** [comment]
@fleimgruber Uh, you should be able to download docsets with `helm-dash-install-docset` now, as this is what changed. Zeal probably doesn't use the `helm-dash` functionality, or does it?

**Comment by fleimgruber** [comment]
Ah, then I misunderstood. I thought the docsets were stored locally as archives and any `helm-dash` lookup would use `tar`. I just tried and installed the Julia docset via `helm-dash-install-docset`. Works Over Here.

**Comment by kidd** [comment]
nice!  Closing this one then.

Thank you all!
