### ISSUE TITLE
`browse-url` fails

### ISSUE THREAD

**Issue by asok** [areina/helm-dash#36]
I'm using Emacs 24.3.1 on Macos. It seems that url browsing does not work. When I try:

```
(browse-url "file:///Users/asok/.docsets/Ruby on Rails.docset/Contents/Resources/Documents/api.rubyonrails.org/v3.2.16/classes/AbstractController/Callbacks/ClassMethods.html#method-i-append_before_filter")
```

In the `*Messages*` I see:

```
#<process open file:///Users/asok/.docsets/Ruby on Rails.docset/Contents/Resources/Documents/api.rubyonrails.org/v3.2.16/classes/AbstractController/Callbacks/ClassMethods.html#method-i-append_before_filter>
```

And no browser's window is opened.
Though when I strip the `#target` part of the url:

```
(browse-url "file:///Users/asok/.docsets/Ruby on Rails.docset/Contents/Resources/Documents/api.rubyonrails.org/v3.2.16/classes/AbstractController/Callbacks/ClassMethods.html")
```

The browser window is opened with the html file.

It might be the bug mentioned [here](http://www.emacswiki.org/emacs/BrowseUrl#toc21) (under the section named: "Bug" in browse-url-default-windows-browser).

Maybe it's worth mentioning that in the README.

**Comment by jasonm23** [comment]
Another way would be to host via a little local webserver and allow helm-dash to have a different base url from `file:///`

**Comment by jasonm23** [comment]
I'm now using this method.

```
(defun start-dash-local-server ()
  "Start a localhost server on port 5000 via a ruby sub process, and serve dash docsets."
  (start-process "docset-local-server" "*docset-local-server*"
                 "ruby" "-run" "-e" "httpd" helm-dash-docsets-path "-p5000"))

(defun browse-url-helm-dash (url)
  "Convert file:///URL to http://localhost:5000/ for use with dash local server"
  (let* ((docsets (concat "file://" (expand-file-name "~/.docsets")))
         (localurl (replace-regexp-in-string (regexp-quote docsets) "http://localhost:5000" url nil 'literal)))
    (unless (processp 'dash-local-server)
      (start-dash-local-server))
    (browse-url localurl)))

(setq helm-dash-browser-func 'browse-url-helm-dash)
```

**Comment by jasonm23** [comment]
Also just tried to open a URL in Google chrome OSX with 

    /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome "file:///Users/jason/index.html#jump"

Seems to work, so I'm trying shell-command / start-process

**Comment by jasonm23** [comment]
This worked.

```
(shell-command "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome \"file:///Users/jason/index.html#jump\"")
```

Safari needs an osascript solution...

Personally I like the localhost server solution, as it doesn't require a specific browser.

**Comment by jasonm23** [comment]
http://apple.stackexchange.com/a/197284/1267

    osascript -e 'open location "file:///Somethingwithan.html#anchor" '

**Comment by markhuyong** [comment]
for mac ox El Captan, spacemacs:
* set os default browser to chrome
* add config to defun dotspacemacs/user-config ()
```emac-lisp
;;helm-dash
  (with-eval-after-load 'dash
    (setq helm-dash-browser-func 'browse-url-default-macosx-browser))

```
