### ISSUE TITLE
helm-dash does not complete (seems does not connect to docsets correctly)

### ISSUE THREAD

**Issue by stardiviner** [areina/helm-dash#54]
I install helm-dash through el-get.
And configure it with:

``` lisp
(require 'helm-dash)

(setq helm-dash-docsets-path (expand-file-name "~/.docsets")
      helm-dash-min-length 3
      ;; helm-dash-completing-read-func 'completing-read ; 'completing-read, 'ido-completing-read
      helm-dash-browser-func 'browse-url ; 'browse-url, 'eww
      ;; helm-dash-connections
      helm-dash-common-docsets '("Ruby" "Ruby on Rails"
                                 "HTML" "CSS" "JavaScript" "CoffeeScript"
                                 "Common_Lisp" "Clojure"
                                 "C" "Go"
                                 "SQLite" "MySQL" "Redis" "MongoDB"
                                 "Qt"
                                 "Vagrant" "Nginx"
                                 )
      ;; helm-dash-docsets
      )
(define-key help-document-map (kbd "C-d") 'helm-dash-at-point)
```

After download docsets with `helm-dash-install-docsets`.
And when I execute `[M-x helm-dash]`. It only show `Ruby nil`
or `Ruby on Rails nil`. I also tried command `helm-dash-active-docsets`.
None of them can work correctly.

**Comment by amitp** [comment]
May I suggest that `helm-dash-sql` use `sqlite3 -list`? That way it no longer matters what format the user prefers in `.sqliterc`. It'd be nice if the user's choice for command line usage does not interfere with the operation of helm-dash.

**Comment by stardiviner** [comment]
Maybe helm-dash should extract `helm-dash-sql`'s `call-process` out a variable called like `helm-dash-sql-parameters`. So that user can specify like `--list`.

**Comment by kidd** [comment]
For now I'll add  '-list' to the hardcoded commandline... I don't foresee many more configs needed... We'll do it when really needed

**Comment by kidd** [comment]
that should do it, right?

**Comment by stardiviner** [comment]
@kidd It's fine.
