### ISSUE TITLE
Docsets from contrib

### ISSUE THREAD

**Issue by jasonm23** [areina/helm-dash#89]
https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets

It would be great if we could install user contributed docsets

**Comment by Kapeli** [comment]
Instructions on how the user contributed docsets are stored and so on can be found in my comment at https://github.com/zealdocs/zeal/issues/170#issuecomment-71310603.

**Comment by jasonm23** [comment]
Thank you @Kapeli

**Comment by kidd** [comment]
try `m-x helm-dash-install-user-docset ` . Currently experimental, ...

**Comment by jasonm23** [comment]
@kidd Ramon, that seems to work fine.

**Comment by kidd** [comment]
:)
