### ISSUE TITLE
How to diagnose helm-dash not showing anything?

### ISSUE THREAD

**Issue by dakrone** [areina/helm-dash#90]
Is there a verbose setting or a flag I can enable to help track down why helm-dash does not show anything? I have two docsets enabled, one activated, sqlite3 on the `$PATH`, but no results are ever returned.

**Comment by areina** [comment]
Hi @dakrone , we just merged a PR that may help you. Upgrade helm-dash to latest version and you will have a debugging buffer containing errors thrown by sqlite. Hope that helps you.
