### ISSUE TITLE
Breaking change in helm-match-plugin

### ISSUE THREAD

**Issue by tjefferson08** [areina/helm-dash#94]
Looks to me like [this commit](https://github.com/emacs-helm/helm/commit/b26db373b005f237efde253616c4db585eca1fd1) in emacs-helm broke the require statement [here](https://github.com/areina/helm-dash/blob/master/helm-dash.el#L40)

Updating the symbol name seems to have fixed it on my local.

**Comment by microamp** [comment]
The PR fixed it for me. Thanks, @tjefferson08!

**Comment by stardiviner** [comment]
me too.

**Comment by To1ne** [comment]
My setup couldn't find `helm-multi-match`. I had to upgrade `helm`. Thanks!
